defaultPortal: McKay
portals:
  - name: McKay
    portalId: 319325
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CO-CmeCPLxIEAA0ABBjdvhMgxamaBiju6QwyGQAHXK72J4j00njJlUqUgnv2AWmJZjQsawc6KAAABEEAAAB4AAAAAAAAAACAAAAAAAAABAAAwAdgAAAAAAAAAAAAAGBCGQAHXK72ehcQWALnYbdWIlQheAa5-ihzKNpKA25hMQ
        expiresAt: '2021-04-22T23:59:31.703Z'
    personalAccessKey: >-
      CiRiOWQxNTczOC01OWQwLTQ4MTgtOTQzNS0xNTZjNjQ5ZjdmNWQQ3b4TGMWpmgYqGQAF5pGCsBatFFochQQ0kPJ3xJ4r4tVm3hc
